# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

install:
  - pip install tox

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy

script:
  - tox -e $TOXENV
#  causing failure
#  - coverage run --source=sample_module setup.py test
